#!/usr/bin/env python3
"""C1a — compare step-matched training arms and emit the decision.

DESIGN §5.2 and PLAN C1a run three arms, not a 2x2 matrix: the no-empty 15-output
control against the 5k-empty 16-output arm at 256x192, and then one additional 224x224
run reusing the winner's data/head contract.

This module reads their `history.json` files and writes the comparison. Two things it
insists on:

**The arms must actually be matched.** It re-reads the recorded step budgets rather than
trusting that they were passed correctly — a mismatched `--override` already launched one
arm with the wrong budget once, and a comparison between differently-trained models is
not an ablation, it is a coincidence.

**Non-empty images seen is reported next to the result.** DESIGN §5.2: under a fixed step
budget the supplement arm necessarily sees ~37% fewer animals, so "the supplement helped"
and "this arm saw fewer animals" pull in opposite directions and the reader needs both
numbers to interpret either.

Usage:
    python -m wildlife_trigger.validate.ablation_compare \
        --runs results/ablations/a/history.json results/ablations/b/history.json \
        --output results/ablations/data_input_decision.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def best_entry(run: dict) -> dict:
    return next(e for e in run["history"] if e["epoch"] == run["best_epoch"])


def load(path: Path) -> dict:
    run = json.loads(path.read_text())
    run["_best"] = best_entry(run)
    return run


def check_matched(runs: list[dict]) -> dict:
    """Confirm the arms really were step-matched before comparing them.

    Matching is a property of the **budget**, not of the steps consumed. Early stopping
    is part of DESIGN §7.2's recipe and is applied identically to both arms, so an arm
    that converges sooner and stops has told us something about itself — it has not
    broken the comparison. But the reader must be able to see it: two arms that consumed
    4,220 and 6,000 steps did not train equally long, and if the shorter one also scored
    lower, "it stopped early" and "it is worse" are different claims.

    So consumed steps are reported alongside, and a large gap is flagged rather than
    silently averaged into a verdict.
    """
    budgets = {r["run_name"]: r["budget"] for r in runs}
    max_steps = {b["max_steps"] for b in budgets.values()}
    head_steps = {b["head_steps"] for b in budgets.values()}
    consumed = {name: b["steps"] for name, b in budgets.items()}

    spread = (
        (max(consumed.values()) - min(consumed.values())) / max(consumed.values())
        if consumed
        else 0.0
    )
    return {
        "max_steps_identical": len(max_steps) == 1,
        "head_steps_identical": len(head_steps) == 1,
        "observed_max_steps": sorted(max_steps),
        "observed_head_steps": sorted(head_steps),
        "steps_consumed": consumed,
        "consumed_spread": round(spread, 4),
        "an_arm_stopped_early": any(
            b["steps"] < b["max_steps"] for b in budgets.values()
        ),
        "per_run": budgets,
        # The budget is what must match. Consumption is reported, not required.
        "matched": len(max_steps) == 1 and len(head_steps) == 1,
    }


def row(run: dict) -> dict:
    best = run["_best"]
    return {
        "run": run["run_name"],
        "classes": len(run["class_names"]),
        "input": f"{run['config']['width']}x{run['config']['height']}",
        "steps": run["budget"]["steps"],
        "effective_epochs": run["budget"]["effective_epochs"],
        "images_seen": run["budget"]["images_seen"],
        "non_empty_seen": run["budget"]["non_empty_images_seen"],
        "selection_score": best["selection_score"]["primary"],
        "cis_f2": best["cis_val_clean"]["frame_f2"],
        "trans_f2": best["trans_val"]["frame_f2"],
        "cis_seq_recall": best["cis_val_clean"]["sequence_balanced_recall"],
        "trans_seq_recall": best["trans_val"]["sequence_balanced_recall"],
        "cis_false_fire": best["cis_val_clean"]["false_fire_rate"],
        "trans_false_fire": best["trans_val"]["false_fire_rate"],
        "best_epoch": run["best_epoch"],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs", required=True, type=Path, nargs="+")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()

    runs = [load(path) for path in args.runs]
    matched = check_matched(runs)
    rows = [row(r) for r in runs]
    rows.sort(key=lambda r: -r["selection_score"])
    winner = rows[0]

    lines = [
        "# C1a — data and input decision",
        "",
        "GENERATED by `wildlife_trigger.validate.ablation_compare`. Every number here",
        "comes from a run's `history.json`; none is retyped.",
        "",
        "## Are the arms actually matched?",
        "",
        f"- identical total step budget: **{matched['max_steps_identical']}** "
        f"({matched['observed_max_steps']})",
        f"- identical phase-A head budget: **{matched['head_steps_identical']}** "
        f"({matched['observed_head_steps']})",
        "",
        "DESIGN §5.2 matches the arms on optimizer steps rather than epochs: the",
        "supplement changes the training set from 13,553 to 18,553 images (+36.9% steps",
        "per epoch), so an epoch-matched comparison would confound *empty data helps*",
        "with *this arm simply trained 37% longer*. The phase-A budget is matched for the",
        "same reason — 5 epochs of head training is 1,055 steps in one arm and 1,445 in",
        "the other.",
        "",
    ]

    if matched["an_arm_stopped_early"]:
        lines += [
            "### An arm stopped early",
            "",
            f"Steps actually consumed: `{matched['steps_consumed']}` "
            f"(spread {matched['consumed_spread']:.1%} of the larger).",
            "",
            "Early stopping is part of DESIGN §7.2's recipe and was applied identically",
            "to both arms, so this does not invalidate the comparison — an arm that",
            "converged sooner has told us something about itself. But the arms did not",
            "train for equally long, so read the score together with the steps:",
            "*it stopped early* and *it is worse* are different claims, and only the",
            "second is about the data.",
            "",
        ]

    lines += [
        "## Results",
        "",
        "Selection score is mean bobcat F2 across cis-val-clean and trans-val at a fixed",
        "0.5 threshold (DESIGN §7.2). C3 calibrates the real operating point; this is a",
        "constant yardstick for comparing candidates, not an operating point.",
        "",
        "| run | outputs | input | steps | eff. epochs | non-empty seen | score | cis F2 | trans F2 | cis seq-recall | trans seq-recall | cis false-fire | trans false-fire |",
        "|---|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for r in rows:
        lines.append(
            f"| `{r['run']}` | {r['classes']} | {r['input']} | {r['steps']} | "
            f"{r['effective_epochs']} | {r['non_empty_seen']:,} | "
            f"**{r['selection_score']:.4f}** | {r['cis_f2']:.4f} | {r['trans_f2']:.4f} | "
            f"{r['cis_seq_recall']:.4f} | {r['trans_seq_recall']:.4f} | "
            f"{r['cis_false_fire']:.4f} | {r['trans_false_fire']:.4f} |"
        )

    lines += [
        "",
        "## Reading the non-empty column",
        "",
        "Under a fixed step budget the supplement arm necessarily sees fewer animal",
        "frames — that is the price of the comparison being about data rather than",
        "compute. DESIGN §5.2 requires this number beside the result precisely so",
        "*the supplement helped* cannot quietly mean *this arm saw more animals*, and",
        "so a supplement arm that loses slightly on bobcat F2 while cutting the empty",
        "false-fire rate can be read for what it is.",
        "",
        "## Decision",
        "",
        f"Highest selection score: **`{winner['run']}`** ({winner['selection_score']:.4f}).",
        "",
    ]

    if not matched["matched"]:
        lines += [
            "> **This comparison is not valid.** The arms do not share a step budget, so",
            "> the difference between them is not attributable to the variable under",
            "> test. Re-run them matched before reading anything above as a result.",
            "",
        ]

    document = "\n".join(lines) + "\n"
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(document)
        print(f"wrote {args.output}")
    print(document)

    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(
            json.dumps({"matched": matched, "rows": rows, "winner": winner["run"]}, indent=2)
            + "\n"
        )

    return 0 if matched["matched"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
