#!/usr/bin/env python3
"""C1a — freeze the canonical Python golden tensors at the selected input shape.

C0 froze the raw fixtures and deliberately left tensor shapes provisional, because the
input contract was still open. C1a closed it at **256x192**, so the tensors can now be
frozen against something that will not move.

These are the reference the C++ preprocessor is checked against (`preprocess.py`'s
docstring promises exactly this, and P1 is the comparison). The point is not that
20 tensors are interesting — it is that a change to any step of DESIGN §5.5's contract,
in either language, stops being silent.

## Three kinds of evidence, because they are not equally strict

**Geometry** — `resized_width/height`, the pads, `pixel_utilisation`. Pure integer
arithmetic on two integers. Identical everywhere, forever, or something is wrong. This is
the part a cross-language comparison can demand exactly, and the part that caught the
utilisation denominator bug.

**The uint8 letterbox hash** — steps 1-4, what the cache stores. Deterministic for a
given OpenCV, and the strongest check available on the pixels themselves.

**The float32 tensor hash** — steps 5-7 on top. Frozen as a *Python-side tripwire*, not
as a cross-language contract. `INTER_LINEAR` and float arithmetic are not promised to be
bit-identical across OpenCV builds, SIMD paths or architectures, and gx10 is ARM while
a reviewer's box may not be. **A C++ parity check must compare tensors within a
tolerance and reserve exactness for the geometry.** Asserting bit-equality across the
language boundary would produce a test that fails for being run somewhere else, which is
worse than no test: it teaches the reader to ignore it.

Summary statistics are recorded beside the hashes so a mismatch can be *diagnosed*
rather than merely detected — a hash says "different", a mean says "the normalisation
constants moved".

Usage:
    python -m wildlife_trigger.validate.golden_tensors \
        --fixtures tests/fixtures/golden_raw.json \
        --images-dir data/raw/extracted/eccv_18_all_images_sm \
        --width 256 --height 192 \
        --output tests/fixtures/golden_tensors_256x192.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np

from ..data.preprocess import PreprocessConfig, decode, letterbox_bgr, normalise


def sha256_array(array: np.ndarray) -> str:
    """Hash the exact bytes, with the shape and dtype bound in.

    Without the header, a (3,192,256) float32 and a (192,256,3) float32 holding the same
    bytes would hash identically — and a transposed tensor is precisely the bug this is
    meant to catch.
    """
    digest = hashlib.sha256()
    digest.update(f"{array.dtype.str}|{array.shape}|".encode())
    digest.update(np.ascontiguousarray(array).tobytes())
    return digest.hexdigest()


def freeze_one(path: Path, config: PreprocessConfig) -> dict:
    """Run the real pipeline. Not a reimplementation of it.

    Everything here goes through the same functions training and the cache builder call.
    A golden file generated by a private copy of the preprocessing would freeze the copy
    and agree with itself forever.
    """
    bgr = decode(path)
    letterbox, info = letterbox_bgr(bgr, config)
    tensor = normalise(letterbox, config)

    return {
        "geometry": {
            "source_width": info.source_width,
            "source_height": info.source_height,
            "resized_width": info.resized_width,
            "resized_height": info.resized_height,
            "pad_left": info.pad_left,
            "pad_top": info.pad_top,
            "target_width": info.target_width,
            "target_height": info.target_height,
            "scale": round(info.scale, 10),
            "pixel_utilisation": round(info.pixel_utilisation(), 6),
        },
        "letterbox_uint8": {
            "shape": list(letterbox.shape),
            "sha256": sha256_array(letterbox),
        },
        "tensor_float32": {
            "shape": list(tensor.shape),
            "sha256": sha256_array(tensor),
            "mean_per_channel": [round(float(x), 6) for x in tensor.mean(axis=(1, 2))],
            "std_per_channel": [round(float(x), 6) for x in tensor.std(axis=(1, 2))],
            "min": round(float(tensor.min()), 6),
            "max": round(float(tensor.max()), 6),
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fixtures", required=True, type=Path)
    parser.add_argument("--images-dir", required=True, type=Path)
    parser.add_argument("--width", type=int, default=256)
    parser.add_argument("--height", type=int, default=192)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    raw = json.loads(args.fixtures.read_text())
    config = PreprocessConfig(width=args.width, height=args.height)

    entries = []
    for fixture in raw["fixtures"]:
        path = args.images_dir / fixture["file_name"]

        # The raw hash is re-checked, not trusted. These tensors are only canonical if
        # they came from the exact bytes C0 froze; a re-downloaded or re-encoded frame
        # would otherwise silently redefine the reference.
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        if digest != fixture["sha256"]:
            raise RuntimeError(
                f"{fixture['file_name']} does not match the hash C0 froze.\n"
                f"  frozen : {fixture['sha256']}\n"
                f"  on disk: {digest}\n"
                "The source image changed. Golden tensors from it would be canonical for "
                "a frame that is no longer the fixture."
            )

        entry = {
            "image_id": fixture["image_id"],
            "file_name": fixture["file_name"],
            "split": fixture["split"],
            "labels": fixture["labels"],
            "raw_sha256": fixture["sha256"],
            "reason": fixture["reason"],
        }
        entry.update(freeze_one(path, config))
        entries.append(entry)

    document = {
        "task": "C1a",
        "input": f"{args.width}x{args.height}",
        "selected_by": (
            "C1a — see results/ablations/data_input_decision.md. 256x192 over 224x224: "
            "the arms are statistically tied on bobcat F2, and 256x192 carries +31.1% "
            "real pixels at -2.0% MACs."
        ),
        "preprocess_fingerprint": config.fingerprint(),
        "count": len(entries),
        "generated_by": "wildlife_trigger.validate.golden_tensors",
        "exactness": {
            "geometry": (
                "EXACT. Integer arithmetic on the source dimensions. A C++ parity check "
                "must match these exactly."
            ),
            "letterbox_uint8.sha256": (
                "EXACT for a given OpenCV build. Steps 1-4, the same bytes the cache "
                "stores."
            ),
            "tensor_float32.sha256": (
                "PYTHON-SIDE TRIPWIRE ONLY. Float arithmetic and INTER_LINEAR are not "
                "bit-identical across OpenCV builds, SIMD paths or architectures. Cross-"
                "language parity must compare within a tolerance and take exactness from "
                "the geometry; a bit-equality assertion across the boundary would fail "
                "for running on a different machine, which teaches readers to ignore it."
            ),
        },
        "fixtures": entries,
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(document, indent=2) + "\n")
    print(f"froze {len(entries)} golden tensors at {args.width}x{args.height} -> {args.output}")

    utilisations = [e["geometry"]["pixel_utilisation"] for e in entries]
    print(
        f"pixel utilisation across fixtures: min {min(utilisations):.4f}, "
        f"max {max(utilisations):.4f}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
